# This is a basic workflow to help you get started with Actions

name: test-report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  nunitPath: nunit25/TestsResultsAdmin-CI.xml
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Capture ctrf json
        run: |-
          Get-ChildItem '${{ github.workspace }}\ctrf\*.json'
        shell: powershell

# These three don't work         
#      - name: Publish Test Report - full path
#        uses: ctrf-io/github-test-reporter@v1
#        with:
#          report-path: '${{ github.workspace }}\ctrf\*.json'
#        if: always()

#      - name: Publish Test Report - relative path - no prefix
#        uses: ctrf-io/github-test-reporter@v1
#       with:
#          report-path: 'ctrf\*.json'
#        if: always()

#      - name: Publish Test Report - relative path - .\
#        uses: ctrf-io/github-test-reporter@v1
#        with:
#          report-path: '.\ctrf\*.json'
#        if: always()

      - name: Publish Test Report - relative path - ./
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/*.json'
          summary-report: true
          test-report: false
          test-list-report: false
          failed-report: false
          fail-rate-report: false
          flaky-report: false
          flaky-rate-report: false
          failed-folded-report: false
          previous-results-report: false
          ai-report: false
          skipped-report: false
          suite-folded-report: false
          suite-list-report: false
          pull-request-report: false
          commit-report: false
          custom-report: false
        if: always()
