# This is a basic workflow to help you get started with Actions

name: test-report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
    
      - name: Generate HTML test report
        uses: rjtngit/nunit-html-action@v1
        if: always()
        with:
          inputXmlPath: TestsResultsAdmin-CI.xml
          outputHtmlPath: test_results/results.html
          
      - name: Upload test artifacts # So you can download the results from the workflow run.
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: test_results
                
